FROM nginx:alpine

COPY html /usr/share/nginx/html

RUN rm /etc/nginx/conf.d/default.conf

COPY default_prod.conf /etc/nginx/conf.d/

EXPOSE 8080

RUN mkdir /var/www/html -p && touch /var/www/html/index.js

ENTRYPOINT [ "/docker-entrypoint.sh" ]

CMD [ "nginx", "-g", "daemon off;" ]