
POST http://localhost:8080/transactions HTTP/1.1
Content-Type: application/json

{
    "account_id_from": "008ef379-ebef-4f0c-9f60-6d5260e6aff3",
    "account_id_to": "a9ed6c13-7db2-46a0-b94e-91aa3845f3c7",
    "amount": 30
}

GET http://localhost:8081/statements/id-retornado-na-criacao-transations HTTP/1.1