
POST http://localhost:8080/clients HTTP/1.1
Content-Type: application/json

{
    "name": "jose",
    "email": "jose@jose"
}

{
  "ID": "eabb08ac-1a84-48d8-947b-df9a14858513",
  "Name": "jose",
  "Email": "jose@jose",
  "CreatedAt": "2023-07-18T20:53:42.926712035-03:00",
  "UpdateAt": "2023-07-18T20:53:42.926712224-03:00"
}
###


POST http://localhost:8080/clients HTTP/1.1
Content-Type: application/json

{
    "name": "maria",
    "email": "maria@maria"
}

{
  "ID": "2ea33027-ede8-44b8-bd5d-25358aacc936",
  "Name": "maria",
  "Email": "maria@maria",
  "CreatedAt": "2023-07-18T20:56:27.347794732-03:00",
  "UpdateAt": "2023-07-18T20:56:27.347795273-03:00"
}

###

POST http://localhost:8080/accounts HTTP/1.1
Content-Type: application/json

{
    "client_id": "2ea33027-ede8-44b8-bd5d-25358aacc936"
}

{
  "ID": "a2cc50da-5a4c-477b-95ef-e767d0ad8c76"
}

###

POST http://localhost:8080/accounts HTTP/1.1
Content-Type: application/json

{
    "client_id": "eabb08ac-1a84-48d8-947b-df9a14858513"
}

{
  "ID": "dc3ad267-0940-425a-980d-d8f94a1e2bbc"
}

POST http://localhost:8080/transactions HTTP/1.1
Content-Type: application/json

{
    "account_id_from": "a2cc50da-5a4c-477b-95ef-e767d0ad8c76",
    "account_id_to": "dc3ad267-0940-425a-980d-d8f94a1e2bbc",
    "amount": 100
}